### ISSUE TITLE
data_process报错: ValueError: '<=50K.' is not in list

### ISSUE THREAD

**Issue by smudag** [yuanbenio/crypten_vfl_demo#4]
```
Traceback (most recent call last):
  File "data_process.py", line 134, in <module>
    arr = convert_csv_to_arr("adult.test.csv", mean_std)
  File "data_process.py", line 102, in convert_csv_to_arr
    arr = df_to_arr(df)
  File "data_process.py", line 56, in df_to_arr
    val = attr_classes[col].index(raw_val)
ValueError: '<=50K.' is not in list
```
<img width="813" alt="image" src="https://user-images.githubusercontent.com/90293674/134603703-07d66967-dc11-4bca-a47d-f36396ad7420.png">

**Comment by mh739025250** [comment]
我刚刚试了下，没有问题

你的adult.test.csv长什么样？可以发来看看么

**Comment by wuzh3nq1** [comment]
需要把test中的50K.替换为50K
